### ISSUE TITLE
Cannot read property "filter" of undefined

### ISSUE THREAD

**Issue by msageryd** [fabiospampinato/vscode-projects-plus-todo-plus#1]
I'm using Project+ and Todo+. Thought I'd try out "Project+ Todo+" for an overview. 

When I select the command "Projects: Todo" i get `Cannot read property "filter" of undefined`

**Comment by fabiospampinato** [comment]
Thanks for reporting the problem, I'll investigate this as soon as I get some free time.

**Comment by fabiospampinato** [comment]
@msageryd I can't reproduce the problem, can you try using v1.4.0 and see if that fixes it?

**Comment by fabiospampinato** [comment]
No needed info provided, I'm closing this.
