### ISSUE TITLE
does't find any TODO :(

### ISSUE THREAD

**Issue by StefanoCecere** [fabiospampinato/vscode-projects-plus-todo-plus#2]
i have 5 projects in Projects+
my TODO are named TODO (default values everywhere)
but it finds nothing "You don't have any todo across your projects"

is it still working with current Code 1.18.1 ?

**Comment by fabiospampinato** [comment]
Are you using the new "home expansion" feature? Basically, are paths written as "~/path/to /project"?

Give me a few days to find the time for this and I'll fix it.

**Comment by StefanoCecere** [comment]
ahhh yes (it was the default value)
i've just set `"projects.useTilde": false` and now it works

better to make it work with Tilde anyway! thanks

**Comment by fabiospampinato** [comment]
Sure, I need to add support for all the things I've been implementing recently in Projects+ and Todo+ :)

**Comment by fabiospampinato** [comment]
Fixed in v1.4.0.

I've also added an option for hiding archives.
