### ISSUE TITLE
How does this extension work?

### ISSUE THREAD

**Issue by sahil48** [fabiospampinato/vscode-projects-plus-todo-plus#3]
I'm a little confused about how to get this extension to start working. Where are todo files supposed to be located?

**Comment by fabiospampinato** [comment]
You need both [Projects+](https://github.com/fabiospampinato/vscode-projects-plus) and [Todo+](https://github.com/fabiospampinato/vscode-todo-plus) installed for this to work.

This extension will read the list of your projects from Projects+, check if they have a file named with the same name as your `"todo.file"` setting in their root, and aggregate all the found todos. 

It also does something similar for embedded todos.
