### ISSUE TITLE
More filter options

### ISSUE THREAD

**Issue by koemii** [fabiospampinato/vscode-projects-plus-todo-plus#4]
I would like to have the option to search in specific folders (not just the whole projects). Maybe recognize my "files.exclude" settings. I always see even the todos of other devs in their libraries. Which arent necessary for me.

**Comment by fabiospampinato** [comment]
> I would like to have the option to search in specific folders

You can already achieve this by filtering by a glob. You can also use the `projectsTodo.filterRegex` setting.

> Maybe recognize my "files.exclude" settings.

Maybe the `todo.embedded.exclude` setting isn't properly used at the moment, if you're using `ag` or `rg` as your embedded todos provider. I'll fix that in the next release.

**Comment by koemii** [comment]
`todo.embedded.exclude` this one helped me. Did'nt know that this command exist. Shame on me here, I guess.

Thanks for the help!

**Comment by fabiospampinato** [comment]
As of v1.6.5 performance should be much better,and `todo.embedded.exclude` should be fully supported.
