### ISSUE TITLE
Spelling error in extension description

### ISSUE THREAD

**Issue by sudoJoe** [fabiospampinato/vscode-projects-plus-todo-plus#7]
Usage
It adds 2 commands to the command palette:

Projects: Todo // Open a file **containg** all your todo files aggregated into one
Projects: Embedded Todos // Open a file **containg** all your embedded todos aggregated into one

Both should be '**containing**', not '**containg**'

**Comment by fabiospampinato** [comment]
Thanks, I've just fixed the typos.
