### ISSUE TITLE
I cannot find you extenstion in my vscode.

### ISSUE THREAD

**Issue by azkia98** [fabiospampinato/vscode-projects-plus-todo-plus#9]
I don't know why I can't find your extension in the market.

![image](https://user-images.githubusercontent.com/28800471/95298659-4a98c600-0889-11eb-8bad-ba8e1192a77f.png)

![image](https://user-images.githubusercontent.com/28800471/95298775-77e57400-0889-11eb-866a-b394083968b2.png)

**Comment by fabiospampinato** [comment]
VScode's extension search is crap.

You can get the one you are looking for from here: https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus

**Comment by fabiospampinato** [comment]
Is that vscode though? It looks like it might be vscodium.
